# Configuration file template
# Modify the values below as deemed nescessary
# See the documentation for more informations
# ------------------------------------------------------------------------------

# Database
# --------

API_url: "http://127.0.0.1:8000/API_test"

# Input and Output paths
# ----------------------
# Path to the output directory, will be created if it doesn´t exist
workdir: /path/to/output/dir
# Path to sample sheet
sample_sheet: /path/to/sample_sheet


# Max number of threads assigned to single jobs
max_threads_per_job: 1

# Clean up workdir on success?
ephemeral: False

# Databases
# ---------
chewie_path: "~/.nrw-geuebt/chewieSnake"

# Additional parameters
# ---------------------
# Organism name
organism: "Genus species"
