# Configuration file template
# Modify the values below as deemed nescessary
# See the documentation for more informations
# ------------------------------------------------------------------------------

# Database
# --------

API_url: "http://127.0.0.1:8010/API_test"

# Input and Output paths
# ----------------------
# Path to the output directory, will be created if it doesn´t exist
workdir: .tests/integration
# Path to sample sheet
sample_sheet: "config/samples.tsv"

# Max number of threads assigned to single jobs
max_threads_per_job: 1

# Clean up workdir on success?
ephemeral: False

# Databases
# ---------
chewie_path: "~/.nrw-geuebt/chewieSnake"
cgmlst_scheme: "data/Listeria_cgmlst_Ruppitsch_chewbbaca/cgmlst"
prodigal: "~/.nrw-geuebt/chewieSnake/chewBBACA/CHEWBBACA/prodigal_training_files/Listeria_monocytogenes.trn"

# Additional parameters
# ---------------------
# Grapetree distance method
distance_method: 3
# The agglomeration method to be used for hierarchical clustering
clustering_method: "single"
# A single distance threshold for the exctraction of sub-trees
cluster_distance: 10
# A list of distance thresholds for subclustering
subcluster_distance: 5
# Prefix for cluster naming
cluster_prefix: "LIS"
organism: "Listeria monocytogenes"
