name: Deploy Documentation

on:
  push:
    branches: [master, main]
    paths:
      - "**.md"
      - "docs/**"
      - "mkdocs.yml"
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SetUp Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Update Contributing
        run: cat CONTRIBUTING.md > docs/contributing.md

      - name: Update Changelog
        run: cat CHANGELOG.md > docs/about/changelog.md

      - name: Update License
        run: cat LICENSE > docs/about/license.md

      - name: Install Dependencies
        run: pip install mkdocs-material

      - name: Cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ github.ref }} 
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install deps
        run: pip install mkdocs-material

      - name: Publish Docs
        run: mkdocs gh-deploy --force
